version: '3.8'
services:

  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  postgres: