from pydantic import BaseSettings


class Settings(BaseSettings):
    project_name: str = ...

    db_user: str = ...
    db_pass: str = ...
    db_host: str = ...
    db_port: int = ...
    db_name: str = ...

    backend_host: str = ...
    backend_port: int = ...

    class Config:
        env_file = ".env"


settings = Settings()
